name: CI/CD Pipeline for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        
      - name: Build project
        run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start Application and Capture Port
        id: start-server
        run: |
          npm run preview | tee server-log.txt &
          sleep 5  # Wait for a few seconds to ensure the server starts
          PORT=$(grep -oP 'http://localhost:\K[0-9]+' server-log.txt)
          echo "Server started on port: $PORT"
          echo "PORT=$PORT" >> $GITHUB_ENV

      - name: Wait for Vite Server
        run: npx wait-on http://localhost:${{ env.PORT }}

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
          config: baseUrl=http://localhost:${{ env.PORT }}

      # To test later
      # - name: Enforce Coverage Threshold
      #   run: |
      #     COVERAGE=$(grep 'Statements' coverage-summary.txt | awk '{print $3}' | tr -d '%')
      #     if [ "$COVERAGE" -lt 80 ]; then
      #       echo "Coverage is below 80%! Failing the pipeline."
      #       exit 1
      #     fi
      #   if: always()